name: Spelling Check

on:
  schedule:
    - cron: "0 0 * * 2"

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'haproxy' }}
    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/codespell-problem-matcher@v1.2.0
    - uses: codespell-project/actions-codespell@master
      with:
        skip: CHANGELOG,Makefile,*.fig,*.pem,./doc/design-thoughts,./doc/internals
        ignore_words_list: ist,ists,hist,wan,ca,cas,que,ans,te,nd,referer,ot,uint,iif,fo,keep-alives,dosen,ifset,thrid,strack,ba,chck,hel,unx,mor,clen,collet,bu,htmp,siz,experim
        uri_ignore_words_list: trafic,ressources
